### PR TITLE
Change isset expression

### LINKED ISSUE #228: isset variable list may include trialing ','
In php 7.3.0, isset is legal for the following code:
```
isset($a,);
```
screenshot 2018-12-20 17 00 06

However, the isset variable list is defined by 
```
isset-intrinsic:
   isset   (   variable-list   )

variable-list:
   variable
   variable-list   ,   variable
```
in `10-expression.md`. 

If we plan to make the spec consistent with current PHP, I can submit a PR to change it as 
```
isset-intrinsic:
   isset   (   isset-variable-list  ','? )

variable-list:
   variable
   variable-list   ,   variable
```

### PR DESCRIPTION
**Pull request by zhujinxuan**
Enable trialing comma in `isset`. Fix #228

### CODE REVIEW

**Comment by nikic** [comment]
This syntax was added as part of https://wiki.php.net/rfc/trailing-comma-function-calls, which also added support for `unset($foo,)` and `call($foo,)`. Maybe you would like to add those two as well?

**Comment by zhujinxuan** [comment]
@nikic Good. I will add them as well tonight :)

**Comment by nikic** [comment]
@zhujinxuan We don't really make a distinction between parse error and fatal error in the langspec. It's only important whether the code is valid or not, the type of error doesn't matter.

**Comment by zhujinxuan** [comment]
@nikic Then shall we remove the ',' in `unkeyed-list-expression-list:` as well?  (As `list(,)` gives a Fatal error)

**Comment by nikic** [comment]
@zhujinxuan Ah, this case is more complicated, because generally `,` is allowed inside list, e.g. you can write `list($a,,,,,$b)`. What is not allowed is a list that consists *only* of `,`, such as `list(,,,,,)`. This kind of rule is best noted in the "Constraints" section, rather than the grammar.

**Comment by zhujinxuan** [comment]
Hi, @nikic .  This PR is ready for review now.

I have made the change for `unset`, functions, methods and new statements.  I have also rebase all commits in case this repo do you squash and merge PR.

For the list statement, I have open a new issue for that.  And if we decide to change list expression documentation, we can make another PR for it.

Merry Christmas

**Comment by nikic** [comment]
Merged as https://github.com/php/php-langspec/commit/197a397cf84bdcd3f896aebf15a73b5fd45a174d. Thanks for taking care of this!

**Pull request closed without merging**
