### PR TITLE
Binary string deprecation

### PR DESCRIPTION
**Pull request by pmmaga**
This PR is part of the Binary string deprecation [RFC](https://wiki.php.net/rfc/binary_string_deprecation).

The PR for php-src can be found [here](https://github.com/php/php-src/pull/2322)

### CODE REVIEW

**Comment by Hywan** [comment]
Keep in mind that the RFC has not been voted yet. Must not merge this PR yet.

**Comment by Hywan** [comment]
And thanks for the PR :-).

**Comment by nikic** [comment]
As the actual removal will only happen in PHP 8, shouldn't this patch only specify deprecation?

**Comment by pmmaga** [comment]
Sure, I can change it to mention the deprecation on the text files then. About the test, should I keep it there as well then?

**Comment by pmmaga** [comment]
I've updated the PR to reflect the deprecation phase.

**Comment by pmmaga** [comment]
Closing as the RFC was rejected

**Comment by padrecedano** [comment]
Do you know why this RFC was rejected? And, it can be deprecated in PHP 8? Thanks.

**Comment by pmmaga** [comment]
@padrecedano you can find the discussion [here](https://externals.io/message/96743) and more [here](https://externals.io/message/98131) The RFC itself is found [here](https://wiki.php.net/rfc/binary_string_deprecation). Given the rejection, it is very unlikely it will get deprecated any time soon.

**Comment by padrecedano** [comment]
@pmmaga  thanks for the fast response and for the discussion links!

**Pull request closed without merging**
