### PR TITLE
Add new V7 operator tokens ?? and <=>

### PR DESCRIPTION
**Pull request by RexJaeschke**
This is my first-ever pull-request for my work in updating the spec for V7. It's small, to the point, and let's me check that I'm understanding the process.

### CODE REVIEW

**Comment by eridal** [comment]
was looking at the others and seems to me that `<=>` should be written `&lt;=&gt;` -- isn't?

**Comment by JoelMarcey** [comment]
Ok, I squashed those two commits together. I will do the same with the other pull request too.

**Comment by RexJaeschke** [comment]
While I did make the suggested changes, I note that & appears directly in the list several times, and not as &amp;. And since < and > used directly render okay, I'm wondering if their escaped versions really are needed.

**Comment by nikic** [comment]
Merged via https://github.com/php/php-langspec/commit/7cdccd1c8de8352e35c0f0e85ced7faaaf50eec3.

**Pull request closed without merging**
